Cherry pick of 128c5fc47735da7267aadacb726ea3d8ce96714c failed
stdout:
Auto-merging payment_mercadopago/models/mercadopago_request.py
Auto-merging payment_mercadopago/controllers/main.py
CONFLICT (content): Merge conflict in payment_mercadopago/controllers/main.py

stderr:
15:29:33.551364 git.c:444               trace: built-in: git cherry-pick 128c5fc47735da7267aadacb726ea3d8ce96714c
error: could not apply 128c5fc... [WIP] Inicio trabajo con el modulo de MP
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: